# Generated by Django 5.0.1 on 2024-01-16 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("softdesk_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="uuid",
        ),
    ]
