# Generated by Django 5.0.1 on 2024-01-22 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("softdesk_api", "0005_alter_comment_issue_alter_contributor_project_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contributor",
            constraint=models.UniqueConstraint(
                fields=("user", "project"), name="unique_contributor_project"
            ),
        ),
    ]
