# Generated by Django 5.0.1 on 2024-01-23 17:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("softdesk_api", "0007_issue_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
