# Generated by Django 5.0.1 on 2024-01-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="can_be_contacted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="can_data_be_shared",
            field=models.BooleanField(default=True),
        ),
    ]
