# Generated by Django 5.0.1 on 2024-01-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_can_be_contacted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_connected",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
