# Generated by Django 5.0.1 on 2024-01-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customuser_last_connected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="last_connected",
            field=models.DateTimeField(blank=True, default=""),
        ),
    ]
